

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: nginx
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
