

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-demo
  template:
    spec:
      containers:
        - name: nginx
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
