

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
